name: Configure Google Cloud SDK tools
description: |
  Download the Google SDK tools and authenticate against the Google Cloud APIs.
inputs:
  project_id:
    required: false
    description: |
      GCP project ID to use.

      By default, it will use the project ID associated with the Service
      Account authenticated.

  service_account_key:
    default: null
    required: false
    description: Service account key to use.

  docker_auth:
    default: true
    required: false
    description: Authenticate Docker against Google Container Registry?

  gcloud_version:
    default: latest
    required: false
    description: Version of the gcloud SDK to install.

  gke_cluster_name:
    default: null
    required: false
    description: Name of a GKE Cluster to authenticate against

  gke_cluster_location:
    default: null
    required: false
    description: |
      Location of the GKE cluster (zonal or regional) to authenticate against.

  kustomize_version:
    required: false
    description: Version of Kustomize to install.

runs:
  using: composite
  steps:
    - name: Google Cloud authentication
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ inputs.service_account_key }}

    - name: Configure Google SDK
      uses: google-github-actions/setup-gcloud@v0.5.1
      with:
        version: ${{ inputs.gcloud_version }}
        project_id: ${{ inputs.project_id }}

    - name: Authenticate for Google Container Registry
      shell: bash
      if: ${{ inputs.docker_auth == 'true'}}
      run: gcloud auth configure-docker

    - name: Authenticate for GKE
      if: ${{ inputs.gke_cluster_name != '' }}
      uses: google-github-actions/get-gke-credentials@v0.7.0
      with:
        cluster_name: ${{ inputs.gke_cluster_name }}
        location: ${{ inputs.gke_cluster_location }}

    - name: Show Google SDK info
      shell: bash
      run: gcloud info

    - name: Configure Kustomize
      uses: stefanprodan/kube-tools@v1
      with:
        kustomize: ${{ inputs.kustomize_version }}
